// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package handler

import (
	"net/http"

	"batchprocess/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/batchProcess",
				Handler: BatchProcessHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/processClient",
				Handler: ProcessClientHandler(serverCtx),
			},
			
		},
	)
}
