// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type BatchProcessReq struct {
	Had_lane_link      HadLaneLink     `json:"had_lane_link,omitempty"`
	Had_lane_mark_line HadLaneMarkLine `json:"had_lane_mark_line,omitempty"`
	Mesh               string          `json:"mesh,omitempty"`
}

type Geometry struct {
	Type        string        `json:"type,omitempty"`
	Coordinates [][][]float64 `json:"coordinates,omitempty"`
}

type HadLaneLink struct {
	Type     string            `json:"type,omitempty"`
	Name     string            `json:"name,omitempty"`
	Features []LaneLinkFeature `json:"features,omitempty"`
}

type HadLaneMarkLine struct {
	Type     string            `json:"type,omitempty"`
	Name     string            `json:"name,omitempty"`
	Features []MarkLinkFeature `json:"features,omitempty"`
}

type LaneLinkFeature struct {
	Type       string             `json:"type,omitempty"`
	Properties LankLinkProperties `json:"properties,omitempty"`
	Geometry   Geometry           `json:"geometry,omitempty"`
}

type LankLinkProperties struct {
	Gid        int64   `json:"gid,omitempty"`
	Id         float64 `json:"id,omitempty"`
	Lane_link_ string  `json:"lane_link_,omitempty"`
	Lg_id      float64 `json:"lg_id,omitempty"`
	Seq_num    float64 `json:"seq_num,omitempty"`
	Create_tim float64 `json:"create_tim,omitempty"`
	Update_tim float64 `json:"update_tim,omitempty"`
	Material_i string  `json:"material_i,omitempty"`
	Operator   string  `json:"operator,omitempty"`
	Version    float64 `json:"version,omitempty"`
	Mesh       string  `json:"mesh,omitempty"`
	Lane_type  float64 `json:"lane_type,omitempty"`
	Is_interse float64 `json:"is_interse,omitempty"`
}

type MarkLinkFeature struct {
	Type       string             `json:"type,omitempty"`
	Properties MarkLinkProperties `json:"properties,omitempty"`
	Geometry   Geometry           `json:"geometry,omitempty"`
}

type MarkLinkProperties struct {
	Gid        int64   `json:"gid,omitempty"`
	Id         float64 `json:"id,omitempty"`
	Lane_mark_ string  `json:"lane_mark_,omitempty"`
	Create_tim float64 `json:"create_tim,omitempty"`
	Update_tim float64 `json:"update_tim,omitempty"`
	Material_i string  `json:"material_i,omitempty"`
	Operator   string  `json:"operator,omitempty"`
	Version    float64 `json:"version,omitempty"`
	Mesh       string  `json:"mesh,omitempty"`
	Mark_type  float64 `json:"mark_type,omitempty"`
	Mark_color float64 `json:"mark_color,omitempty"`
	Mark_width float64 `json:"mark_width,omitempty"`
	Left_lane_ float64 `json:"left_lane_,omitempty"`
	Right_lane float64 `json:"right_lane,omitempty"`
}

type ProcessClientReq struct {
	LaneOffset int32 `json:"laneOffset"`
	LaneLimit  int32 `json:"laneLimit"`
	MarkOffset int32 `json:"markOffset"`
	MarkLimit  int32 `json:"markLimit"`
}

type ErrorResponse struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}
